/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 26 17:44:20 CET 2019
 */

package eu.stamp.botsing;

import org.junit.Test;
import static org.junit.Assert.*;

public class Fraction_ESTest {
  @Test
  public void notGeneratedAnyTest() {
    // EvoSuite did not generate any tests
  }
}
